#!/bin/sh

# Arrange
URL="https://github.com/neovim/neovim/releases/download/v0.11.2/nvim-linux-x86_64.appimage"
BIN="$HOME/.local/bin"
TARGET="nvim"
TARGET_PATH="$BIN/$TARGET"
LINE="export PATH=\"\$HOME/.local/bin:\$PATH\""
PROFILE="$HOME/.profile"
SUCCESS_COLOR="$(printf '\033[1;32m')"
RESET_COLOR="$(printf '\033[0m')"

# Act
mkdir -p "$BIN"
wget -q "$URL" -O "$TARGET_PATH"
chmod +x "$TARGET_PATH"

grep -qxF "$LINE" "$PROFILE" || echo "$LINE" >> "$PROFILE"

# shellcheck disable=SC1090
. "$PROFILE"


# Assert
if command -v "$TARGET" >/dev/null 2>&1; then
  printf "%s[ ok ]%s Neovim instalado em: %s\n" "$SUCCESS_COLOR" "$RESET_COLOR" "$TARGET_PATH"
  printf "%s[ ok ]%s PATH contém ~/.local/bin\n" "$SUCCESS_COLOR" "$RESET_COLOR"
else
  printf "%s[ ! ]%s Erro: Neovim não disponível no PATH\n" "$SUCCESS_COLOR" "$RESET_COLOR"
fi

